//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UkwaSolrMock {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UkwaSolrMock.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///&quot;responseHeader&quot;:{
        ///&quot;zkConnected&quot;:true,
        ///&quot;status&quot;:0,
        ///&quot;QTime&quot;:59,
        ///&quot;params&quot;:{
        ///&quot;facet.range&quot;:&quot;{!ex=filter}crawl_date&quot;,
        ///&quot;facet.range.gap&quot;:&quot;+1YEAR&quot;,
        ///&quot;facet.field&quot;:[&quot;{!ex=filter}public_suffix&quot;,
        ///&quot;{!ex=filter}content_type_norm&quot;,
        ///&quot;{!ex=filter}host&quot;,
        ///&quot;{!ex=filter}domain&quot;,
        ///&quot;{!ex=filter}collection&quot;],
        ///&quot;hl&quot;:&quot;true&quot;,
        ///&quot;indent&quot;:&quot;on&quot;,
        ///&quot;fl&quot;:&quot;id,title,crawl_date,url,wayback_date,domain,access_terms&quot;,
        ///&quot;start&quot;:&quot;0&quot;,
        ///&quot;sort&quot;:&quot;&quot;,
        ///&quot;fq&quot;:[&quot;access_terms:OA&quot;,
        ///&quot;&quot;,
        ///&quot;{!tag=filter}content_type_norm:[&apos;&apos; TO *]&quot;,
        ///&quot;{!tag=filt [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SearchResponse {
            get {
                return ResourceManager.GetString("SearchResponse", resourceCulture);
            }
        }
    }
}
