//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UkwaSolrMock {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UkwaSolrMock.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///&lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;response&gt;
        ///
        ///&lt;lst name=&quot;responseHeader&quot;&gt;
        ///  &lt;bool name=&quot;zkConnected&quot;&gt;true&lt;/bool&gt;
        ///  &lt;int name=&quot;status&quot;&gt;0&lt;/int&gt;
        ///  &lt;int name=&quot;QTime&quot;&gt;20&lt;/int&gt;
        ///  &lt;lst name=&quot;params&quot;&gt;
        ///    &lt;str name=&quot;q&quot;&gt;text:Bruce Dessau&lt;/str&gt;
        ///    &lt;str name=&quot;indent&quot;&gt;on&lt;/str&gt;
        ///  &lt;/lst&gt;
        ///&lt;/lst&gt;
        ///&lt;result name=&quot;response&quot; numFound=&quot;64846&quot; start=&quot;0&quot; maxScore=&quot;7.893731&quot;&gt;
        ///  &lt;doc&gt;
        ///    &lt;str name=&quot;id&quot;&gt;sha1:7FTX2XOZJHYUMOHVJMG2BTBXE6YLW6MU/WM4OYCYCMRVPim2Uw5xOfA==&lt;/str&gt;
        ///    &lt;str name=&quot;source_file&quot;&gt;BL-20130714 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SearchResponse {
            get {
                return ResourceManager.GetString("SearchResponse", resourceCulture);
            }
        }
    }
}
